spring.application.name=Luxe-Store
server.port=8080

# =========================================================
# CONFIGURACIÓN DEL SISTEMA
# Front y Back con Spring Boot y Thymeleaf
# Almacenamiento en Memoria del servidor (Java Collections / ConcurrentHashMap)
# Rúbrica Avance 2: Formularios de ingreso grabados en memoria, listado, consulta y eliminación
# =========================================================
spring.thymeleaf.cache=false
