spring.application.name=Luxe-Store
server.port=8080

# =========================================================
# CONFIGURACIÓN DE BASE DE DATOS EMBEBIDA H2 (FÁCIL / ZERO-SETUP)
# =========================================================
spring.datasource.url=jdbc:h2:mem:luxedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console activa en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CONFIGURACIÓN HIBERNATE / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# =========================================================
# PARA MIGRAR A POSTGRESQL (Solo descomentar estas líneas):
# =========================================================
# spring.datasource.url=jdbc:postgresql://localhost:5432/luxe_db
# spring.datasource.username=postgres
# spring.datasource.password=1234
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
