spring.application.name=Luxe-Store
server.port=8080

# =========================================================
# CONFIGURACIÓN DE ALMACENAMIENTO LOCAL Y EN MEMORIA
# Proyecto Luxe-Store: Front & Back con Spring Boot y Thymeleaf
# Almacenamiento local en Memoria del servidor y LocalStorage en cliente (Sin H2)
# =========================================================
spring.thymeleaf.cache=false
